// Central tournament setup.
// To trial another event, change this file plus your Vercel env vars:
// SLASH_GOLF_TOURN_ID, SLASH_GOLF_YEAR, TOURNAMENT_STATE_ID.

export const tournamentConfig = {
  majorLabel: '154TH OPEN CHAMPIONSHIP',
  title: 'THE OPEN PICK 3 LIVE',
  venue: 'Royal Birkdale Golf Club',
  location: 'Southport, Merseyside, England',
  dates: 'July 16–19, 2026',
  prizePool: '$1,825',
  tournamentTimezone: 'America/Chicago',
  jackpotRule: 'To win, your picks must include the Champion Golfer of the Year. If no punter selects them, the prize pool jackpots.',
  heroImage: 'https://images.unsplash.com/photo-1592919505780-303950717480?auto=format&fit=crop&w=2400&q=80'
};

export const poolEntries = [
  { player: 'Barty', picks: ['Tony Finau', 'Sungjae Im', 'Tom Kim'] },
  { player: 'Enright', picks: ['Jordan Spieth', 'Max Homa', 'J.T. Poston'] },
  { player: 'Roche SES', picks: ['Davis Thompson', 'Ben Griffin', 'Keith Mitchell'] },
  { player: 'Kitch', picks: ['Tony Finau', 'Rickie Fowler', 'Aldrich Potgieter'] },
  { player: 'Brom', picks: ['Sungjae Im', 'Tom Kim', 'Max Homa'] },
  { player: 'Shaw', picks: ['Jordan Spieth', 'Keegan Bradley', 'Taylor Pendrith'] },
  { player: 'Brian Irish', picks: ['Tony Finau', 'Davis Thompson', 'Lucas Glover'] },
  { player: 'Jonesy', picks: ['Sungjae Im', 'Max Homa', 'Tom Hoge'] },
  { player: 'Haycock Snr', picks: ['Jordan Spieth', 'Mackenzie Hughes', 'Adam Svensson'] },
  { player: 'Mal J', picks: ['Tom Kim', 'Ben Griffin', 'Andrew Novak'] },

  { player: 'Doc Campbell', picks: ['Tony Finau', 'Sungjae Im', 'Jordan Spieth'] },
  { player: 'T Coleman', picks: ['Tom Kim', 'Max Homa', 'Keith Mitchell'] },
  { player: 'A Rose', picks: ['Davis Thompson', 'J.T. Poston', 'Ben Griffin'] },
  { player: 'D Haycock', picks: ['Tony Finau', 'Keegan Bradley', 'Rickie Fowler'] },
  { player: 'P Langley', picks: ['Sungjae Im', 'Tom Kim', 'Taylor Pendrith'] },
  { player: 'T Wallace', picks: ['Jordan Spieth', 'Max Homa', 'Lucas Glover'] },
  { player: 'K Ferg', picks: ['Tony Finau', 'Aldrich Potgieter', 'Chris Gotterup'] },
  { player: 'JB', picks: ['Sungjae Im', 'Keith Mitchell', 'Davis Thompson'] },
  { player: 'D McCarthy', picks: ['Tom Kim', 'J.T. Poston', 'Adam Svensson'] },
  { player: 'Nath Ferg', picks: ['Jordan Spieth', 'Ben Griffin', 'Andrew Novak'] },

  { player: 'Muzza T', picks: ['Tony Finau', 'Max Homa', 'Tom Kim'] },
  { player: 'D Donnelly', picks: ['Sungjae Im', 'Davis Thompson', 'Mackenzie Hughes'] },
  { player: 'Hancock', picks: ['Jordan Spieth', 'Rickie Fowler', 'Taylor Moore'] },
  { player: 'B Ashford', picks: ['Tom Kim', 'Keegan Bradley', 'Aldrich Potgieter'] },
  { player: 'Bradley C', picks: ['Tony Finau', 'Ben Griffin', 'J.T. Poston'] },
  { player: 'Sloanie', picks: ['Sungjae Im', 'Max Homa', 'Keith Mitchell'] },
  { player: 'R Fowler', picks: ['Jordan Spieth', 'Lucas Glover', 'Tom Hoge'] },
  { player: 'Sparky', picks: ['Davis Thompson', 'Chris Gotterup', 'Andrew Novak'] },
  { player: 'Barley', picks: ['Tony Finau', 'Tom Kim', 'Rickie Fowler'] },
  { player: 'Pete Holly', picks: ['Sungjae Im', 'Jordan Spieth', 'Max Homa'] },

  { player: 'Timmy S', picks: ['Taylor Pendrith', 'J.T. Poston', 'Keith Mitchell'] },
  { player: 'Mr Grant', picks: ['Tony Finau', 'Davis Thompson', 'Ben Griffin'] },
  { player: 'Greg B', picks: ['Tom Kim', 'Mackenzie Hughes', 'Adam Svensson'] },
  { player: 'JD Boy', picks: ['Sungjae Im', 'Keegan Bradley', 'Lucas Glover'] },
  { player: 'Mr Manson', picks: ['Jordan Spieth', 'Aldrich Potgieter', 'Max Homa'] },
  { player: 'Up the Wahs', picks: ['Tony Finau', 'Tom Kim', 'J.T. Poston'] },
  { player: 'G Ponting', picks: ['Sungjae Im', 'Keith Mitchell', 'Chris Gotterup'] },
  { player: 'R McKnight', picks: ['Jordan Spieth', 'Davis Thompson', 'Rickie Fowler'] },
  { player: 'Chalkey', picks: ['Max Homa', 'Ben Griffin', 'Taylor Moore'] },
  { player: 'Budgie', picks: ['Tom Kim', 'Tony Finau', 'Andrew Novak'] },

  { player: 'Lamming', picks: ['Jordan Spieth', 'J.T. Poston', 'Adam Svensson'] },
  { player: 'A Bull', picks: ['Sungjae Im', 'Davis Thompson', 'Max Homa'] },
  { player: 'Lynda R', picks: ['Tony Finau', 'Lucas Glover', 'Mackenzie Hughes'] },
  { player: 'Cam P', picks: ['Tom Kim', 'Rickie Fowler', 'Keith Mitchell'] },
  { player: 'Wazza SB', picks: ['Jordan Spieth', 'Keegan Bradley', 'Ben Griffin'] },
  { player: 'Mac The Knife', picks: ['Aldrich Potgieter', 'Chris Gotterup', 'Andrew Novak'] },
  { player: 'Crusader', picks: ['Tony Finau', 'Sungjae Im', 'Max Homa'] },
  { player: 'Maccas', picks: ['Tom Kim', 'Davis Thompson', 'Taylor Pendrith'] },
  { player: 'Matt B', picks: ['Jordan Spieth', 'J.T. Poston', 'Keith Mitchell'] },
  { player: 'The Wrangler', picks: ['Tony Finau', 'Rickie Fowler', 'Ben Griffin'] },

  { player: 'AD', picks: ['Sungjae Im', 'Tom Kim', 'Lucas Glover'] },
  { player: 'J Turner', picks: ['Jordan Spieth', 'Max Homa', 'Adam Svensson'] },
  { player: 'M Sanders', picks: ['Davis Thompson', 'Keegan Bradley', 'Taylor Moore'] },
  { player: 'Nick Fitz', picks: ['Tony Finau', 'J.T. Poston', 'Mackenzie Hughes'] },
  { player: 'T Rowe', picks: ['Sungjae Im', 'Aldrich Potgieter', 'Chris Gotterup'] },
  { player: 'J Tilley', picks: ['Tom Kim', 'Keith Mitchell', 'Andrew Novak'] },
  { player: 'Arnie Palmer', picks: ['Jordan Spieth', 'Davis Thompson', 'Lucas Glover'] },
  { player: 'Kimbo Slice', picks: ['Tony Finau', 'Max Homa', 'Ben Griffin'] },
  { player: 'L Adams', picks: ['Sungjae Im', 'Rickie Fowler', 'Taylor Pendrith'] },
  { player: 'K McGinness', picks: ['Tom Kim', 'J.T. Poston', 'Adam Svensson'] },

  { player: 'Baylis', picks: ['Tony Finau', 'Davis Thompson', 'Keith Mitchell'] },
  { player: 'D Tucker', picks: ['Jordan Spieth', 'Max Homa', 'Mackenzie Hughes'] },
  { player: 'Kev Martin', picks: ['Sungjae Im', 'Tom Kim', 'Ben Griffin'] },
  { player: 'P Mac', picks: ['Tony Finau', 'Keegan Bradley', 'Lucas Glover'] },
  { player: 'J Barbour', picks: ['Jordan Spieth', 'Rickie Fowler', 'Andrew Novak'] },
  { player: 'P Lund', picks: ['Davis Thompson', 'J.T. Poston', 'Taylor Moore'] },
  { player: 'Trump H', picks: ['Tom Kim', 'Aldrich Potgieter', 'Chris Gotterup'] },
  { player: 'John Edge', picks: ['Tony Finau', 'Max Homa', 'Adam Svensson'] },
  { player: 'Trent W', picks: ['Sungjae Im', 'Keith Mitchell', 'Taylor Pendrith'] },
  { player: 'Sir Steve', picks: ['Jordan Spieth', 'Ben Griffin', 'Mackenzie Hughes'] },
  { player: 'Nat M', picks: ['Tony Finau', 'Tom Kim', 'Davis Thompson'] },
  { player: 'Spinetto', picks: ['Sungjae Im', 'Max Homa', 'J.T. Poston'] }
];
