// Central tournament setup.
// To trial another event, change this file plus your Vercel env vars:
// SLASH_GOLF_TOURN_ID, SLASH_GOLF_YEAR, TOURNAMENT_STATE_ID.

export const tournamentConfig = {
  majorLabel: '154TH OPEN CHAMPIONSHIP',
  title: 'THE OPEN PICK 3 LIVE',
  venue: 'Royal Birkdale Golf Club',
  location: 'Southport, Merseyside, England',
  dates: 'July 16–19, 2026',
  prizePool: '$1,750',
  tournamentTimezone: 'America/Toronto',
  jackpotRule: 'To win, your picks must include the Champion Golfer of the Year. If no punter selects them, the prize pool jackpots.',
  heroImage: 'https://images.unsplash.com/photo-1592919505780-303950717480?auto=format&fit=crop&w=2400&q=80'
};

export const poolEntries = [
  { player: 'Barty', picks: ['Collin Morikawa', 'Tommy Fleetwood', 'Corey Conners'] },
  { player: 'Enright', picks: ['Collin Morikawa', 'Tommy Fleetwood', 'Sam Burns'] },
  { player: 'Roche SES', picks: ['Tommy Fleetwood', 'Corey Conners', 'Robert MacIntyre'] },
  { player: 'Kitch', picks: ['Shane Lowry', 'Robert MacIntyre', 'Ryan Fox'] },
  { player: 'Brom', picks: ['Collin Morikawa', 'Sam Burns', 'Max Homa'] },
  { player: 'Shaw', picks: ['Tommy Fleetwood', 'Justin Rose', 'Corey Conners'] },
  { player: 'Brian Irish', picks: ['Viktor Hovland', 'Shane Lowry', 'Tony Finau'] },
  { player: 'Jonesy', picks: ['Collin Morikawa', 'Corey Conners', 'Tommy Fleetwood'] },
  { player: 'Haycock Snr', picks: ['Robert MacIntyre', 'Ryan Fox', 'Nick Taylor'] },
  { player: 'Mal J', picks: ['Sam Burns', 'Matt Fitzpatrick', 'Aaron Rai'] },

  { player: 'Doc Campbell', picks: ['Collin Morikawa', 'Robert MacIntyre', 'Mackenzie Hughes'] },
  { player: 'T Coleman', picks: ['Viktor Hovland', 'Brooks Koepka', 'Tom Kim'] },
  { player: 'A Rose', picks: ['Tommy Fleetwood', 'Corey Conners', 'Justin Rose'] },
  { player: 'D Haycock', picks: ['Shane Lowry', 'Sam Burns', 'Taylor Pendrith'] },
  { player: 'P Langley', picks: ['Collin Morikawa', 'Tony Finau', 'Corey Conners'] },
  { player: 'T Wallace', picks: ['Sam Burns', 'Matt Fitzpatrick', 'Max Homa'] },
  { player: 'K Ferg', picks: ['Tommy Fleetwood', 'Corey Conners', 'Ryan Fox'] },
  { player: 'JB', picks: ['Collin Morikawa', 'Brooks Koepka', 'Nick Taylor'] },
  { player: 'D McCarthy', picks: ['Viktor Hovland', 'Robert MacIntyre', 'Aaron Rai'] },
  { player: 'Nath Ferg', picks: ['Shane Lowry', 'Matt Fitzpatrick', 'Taylor Pendrith'] },

  { player: 'Muzza T', picks: ['Collin Morikawa', 'Tommy Fleetwood', 'Ryan Fox'] },
  { player: 'D Donnelly', picks: ['Tommy Fleetwood', 'Sam Burns', 'Corey Conners'] },
  { player: 'Hancock', picks: ['Viktor Hovland', 'Robert MacIntyre', 'Tony Finau'] },
  { player: 'B Ashford', picks: ['Shane Lowry', 'Brooks Koepka', 'Max Homa'] },
  { player: 'Bradley C', picks: ['Collin Morikawa', 'Corey Conners', 'Justin Rose'] },
  { player: 'Sloanie', picks: ['Tommy Fleetwood', 'Ryan Fox', 'Mackenzie Hughes'] },
  { player: 'R Fowler', picks: ['Sam Burns', 'Tony Finau', 'Tom Kim'] },
  { player: 'Sparky', picks: ['Collin Morikawa', 'Max Homa', 'Aaron Rai'] },
  { player: 'Barley', picks: ['Viktor Hovland', 'Tommy Fleetwood', 'Sahith Theegala'] },
  { player: 'Pete Holly', picks: ['Shane Lowry', 'Corey Conners', 'Nick Taylor'] },

  { player: 'Timmy S', picks: ['Collin Morikawa', 'Tommy Fleetwood', 'Sam Burns'] },
  { player: 'Mr Grant', picks: ['Viktor Hovland', 'Corey Conners', 'Taylor Pendrith'] },
  { player: 'Greg B', picks: ['Shane Lowry', 'Robert MacIntyre', 'Justin Rose'] },
  { player: 'JD Boy', picks: ['Collin Morikawa', 'Tommy Fleetwood', 'Brooks Koepka'] },
  { player: 'Mr Manson', picks: ['Tommy Fleetwood', 'Tony Finau', 'Max Homa'] },
  { player: 'G Ponting', picks: ['Viktor Hovland', 'Matt Fitzpatrick', 'Ryan Fox'] },
  { player: 'R McKnight', picks: ['Collin Morikawa', 'Corey Conners', 'Mackenzie Hughes'] },
  { player: 'Chalkey', picks: ['Shane Lowry', 'Sam Burns', 'Nick Taylor'] },
  { player: 'Budgie', picks: ['Tommy Fleetwood', 'Robert MacIntyre', 'Aaron Rai'] },
  { player: 'Lamming', picks: ['Collin Morikawa', 'Justin Rose', 'Taylor Pendrith'] },

  { player: 'A Bull', picks: ['Viktor Hovland', 'Tommy Fleetwood', 'Corey Conners'] },
  { player: 'Lynda R', picks: ['Tommy Fleetwood', 'Brooks Koepka', 'Mackenzie Hughes'] },
  { player: 'Cam P', picks: ['Shane Lowry', 'Tony Finau', 'Ryan Fox'] },
  { player: 'Wazza SB', picks: ['Collin Morikawa', 'Sam Burns', 'Matt Fitzpatrick'] },
  { player: 'Mac The Knife', picks: ['Sam Burns', 'Max Homa', 'Corey Conners'] },
  { player: 'Crusader', picks: ['Tommy Fleetwood', 'Robert MacIntyre', 'Nick Taylor'] },
  { player: 'Maccas', picks: ['Viktor Hovland', 'Ryan Fox', 'Tom Kim'] },
  { player: 'Matt B', picks: ['Collin Morikawa', 'Tommy Fleetwood', 'Corey Conners'] },
  { player: 'The Wrangler', picks: ['Shane Lowry', 'Tony Finau', 'Justin Rose'] },
  { player: 'AD', picks: ['Sam Burns', 'Aaron Rai', 'Mackenzie Hughes'] },

  { player: 'J Turner', picks: ['Collin Morikawa', 'Corey Conners', 'Nick Taylor'] },
  { player: 'M Sanders', picks: ['Viktor Hovland', 'Robert MacIntyre', 'Max Homa'] },
  { player: 'Nick Fitz', picks: ['Tommy Fleetwood', 'Matt Fitzpatrick', 'Corey Conners'] },
  { player: 'M Little', picks: ['Shane Lowry', 'Ryan Fox', 'Sam Burns'] },
  { player: 'T Rowe', picks: ['Collin Morikawa', 'Justin Rose', 'Robert MacIntyre'] },
  { player: 'J Tilley', picks: ['Tommy Fleetwood', 'Sam Burns', 'Taylor Pendrith'] },
  { player: 'Arnie Palmer', picks: ['Viktor Hovland', 'Brooks Koepka', 'Aaron Rai'] },
  { player: 'K. Sanders', picks: ['Collin Morikawa', 'Mackenzie Hughes', 'Ryan Fox'] },
  { player: 'L Adams', picks: ['Shane Lowry', 'Corey Conners', 'Max Homa'] },
  { player: 'K McGinness', picks: ['Tommy Fleetwood', 'Justin Rose', 'Nick Taylor'] },

  { player: 'Baylis', picks: ['Collin Morikawa', 'Tommy Fleetwood', 'Tony Finau'] },
  { player: 'D Tucker', picks: ['Viktor Hovland', 'Sam Burns', 'Corey Conners'] },
  { player: 'Kev Martin', picks: ['Tommy Fleetwood', 'Ryan Fox', 'Matt Fitzpatrick'] },
  { player: 'P Mac', picks: ['Shane Lowry', 'Brooks Koepka', 'Tom Kim'] },
  { player: 'J Barbour', picks: ['Collin Morikawa', 'Corey Conners', 'Sam Burns'] },
  { player: 'P Lund', picks: ['Tommy Fleetwood', 'Robert MacIntyre', 'Mackenzie Hughes'] },
  { player: 'Trump H', picks: ['Viktor Hovland', 'Tony Finau', 'Justin Rose'] },
  { player: 'John Edge', picks: ['Collin Morikawa', 'Sam Burns', 'Matt Fitzpatrick'] },
  { player: 'Trent W', picks: ['Shane Lowry', 'Nick Taylor', 'Taylor Pendrith'] },
  { player: 'Sir Steve', picks: ['Tommy Fleetwood', 'Corey Conners', 'Aaron Rai'] },
  { player: 'Nat', picks: ['Tommy Fleetwood', 'Ryan Fox', 'Matt Fitzpatrick'] },
  { player: 'Up the Wahs', picks: ['Tommy Fleetwood', 'Corey Conners', 'Justin Rose'] }
];
